config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles
  resources :categories, only: %i[show]
  root to: 'articles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :categories, :image, :title
  mount_uploader :image, ImageUploader
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories
  has_many :votes
  scope :most_voted, lambda {
    left_joins(:votes)
      .group(:id)
      .order('COUNT(articles.id) DESC')
      .first
  }
  has_rich_text :text
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  validates :name, length: { in: 3..15 }
  validates :priority, uniqueness: true
  friendly_id :name, use: :slugged

  has_and_belongs_to_many :articles

  def self.categories_name
    Category.distinct.pluck(:name)
  end

  def most_recent_article
    articles.order('created_at desc').first
  end

  def self.top(number)
    order('priority').limit(number)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :name, length: { in: 3..20 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :user_id, uniqueness: { scope: :article_id, message: 'A user can only vote once in an article' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  # def after_sign_in_path_for(_resource_or_scope)
  # root_path
  # end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[create new]

  def index; end

  def new; end

  def create
    @article = Article.new(article_params)
    @categories = Category.find(params[:categories])
    @article.categories = @categories
    @article.author_id = current_user.id
    @article.save

    if @article.save
      redirect_to root_path, notice: 'Article was successfully created.'
    else
      render :index, alert: 'Article was not created.'
    end
  end

  private

  def article_params
    params.require(:article).permit(%i[title image text])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.friendly.find(params[:id])
    @articles = @category.articles.order(created_at: :desc).limit(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/index.html.erb
<div class="main d-flex flex-column">

  <div class="top-row d-flex gradient-bottom">
    <div class="main-article d-flex justify-content-end flex-column">

      <div class="image"
        style='background-image: url("<%= Article.most_voted.image.url %>");'>
      </div>

      <div class="content most-voted-content">
        <h2 class="text-primary d-block z-top">
          <%= Article.most_voted.title %>
        </h2>
        <span class="m-0 p-0 d-block z-top text-white most-voted-article-text">
            <%= simple_format(truncate(Article.most_voted.text.to_plain_text, length: 500)) %>
        </span>
      </div>
    </div>

    <div class="weather-forecast ">
      <div class="image"
        style='background-image: url("https://source.unsplash.com/featured/?Winter");
        '>
      </div>
    </div>
  </div>

  <div class="bottom-row d-flex">
    <% Category.top(4).each do |category| %>
      <div class="gradient-top-bottom position-relative">

        <div class="image"
          style='background-image: url("<%= category.most_recent_article.image.url %>");'>
        </div>
        <h3 class="d-inline-block mt-3 ml-3 category-name">
          <%= link_to("#{category.name}", "categories/#{category.name.downcase}") %>
        </h3>

        <h4 class="category-title">
          <%= category.most_recent_article.title %>
        </h4>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<h2>Log in</h2>

<div class="container main-height">
  <%= form_for :article, url: articles_path do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, autocomplete: "Title", class: 'form-control' %>
    </div>

    <div class="w-100">
      <div class="trix">
        <%= f.label :text %>
        <%= f.rich_text_area :text, autocomplete: "Text", class: 'custom-height col'%>
      </div>
    </div>

    <%= f.label :categories %>
    <div class="d-flex justify-content-between">
    <% Category.all.each do |category| %>
      <div>
       <%= check_box_tag "categories[]", category.id %>
       <%= category.name %>
      </div>
    <% end %>
    </div>

    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, autocomplete: "image", class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit "Create Article", class: 'form-control btn btn-outline-primary' %>
    </div>

  </div>
<% end %>

app/views/categories/show.html.erb
<div class="wrapper">
  <% @articles.each_with_index do |article, i| %>
    <div class="article-container d-inline-block h-50 w-50 m-0 p-0">
      <div class="article d-flex flex-row<%= 'flex-row-reverse' if i >= 2 %>">
        <div class="square">
          <div class="article"
            style='background-image: url("<%= article.image.url %>");'>
          </div>
        </div>
        <div class="square p-3">
          <h2 class="name d-inline-block">
            <%= @category.name %>
          </h2>
          <h3 class="article-title">
            <%= article.title %>
          </h3>
          <span class="article-text">
            <%= simple_format(truncate(article.text.to_plain_text, length: 500 )) %>
          </span>
          <%# <%= link_to('Read More', article_path) %1> %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="d-flex justify-content-between align-items-center p-4">
  <div></div>
  <div class="center">
    <a href="">Privacy Policy</a>
    <a href="">Terms and Conditons</a>
    <span class="text-white">Copyright 2014. All rights reserved.</span>
  </div>
  <div></div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar text-muted d-flex align-items-center">
  <div class="logo-container h-100">
    <%= image_tag "logo-marrom.svg", class: 'logo d-none d-lg-block'%>
  </div>

  <div class="categories">
    <%= link_to("Home", root_path, class: "link") %>
    <%= link_to("Write an article", new_article_path, class: "link") %>
    <% Category.categories_name.each do |category| %>
    <%= link_to("#{category}", category_path(category.downcase), class: "category") %>
    <% end %>
  </div>

  <ul class="user-interaction d-flex flex-row list-unstyled justify-content-center p-0 m-0">
    <% if !user_signed_in? && controller_name != 'sessions' %>
      <li class=''>
        <%= link_to('LOGIN', new_user_session_path, class: "text-decoration-none text-brown")  %>
      </li>
    <% end %>

    <% if !user_signed_in? && controller_name != 'registrations' %>
      <li class=''>
        <%= link_to('REGISTER', new_user_registration_path, class: "text-decoration-none ml-1 text-brown")  %>
      </li>
    <% end %>

    <% if user_signed_in? && controller_name != 'users' %>
      <li class=''>
          <i class="fa fa-user-circle-o text-white"></i>
          <%= content_tag(:span, current_user.name) %>
      </li>
      <% end %>

      <% if user_signed_in? %>
        <li class=''>
          <%= link_to('LOGOUT', destroy_user_session_path, method: :delete, class: "text-decoration-none text-brown", id:"log-out")  %>
        </li>
      <% end %>

    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>realrth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="m-brown">
      <%= render '/layouts/header' %>
      <%= yield %>
    </div>
      <%= render '/layouts/footer' %>
  </body>
</html>